version: "3.8"

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: "gomysqldb"
    environment:
      - MYSQL_DATABASE=godb
      - MYSQL_ROOT_PASSWORD=leandrosc
      - MYSQL_USER=leandrosc
      - MYSQL_PASSWORD=leandrosc
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

#  go_db_service:
#    image: "postgres"
#    container_name: "gopostgredb"
#    environment:
#      - POSTGRES_USER=edteam
#      - POSTGRES_PASSWORD=edteam
#      - POSTGRES_DB=godb

#    ports:
#      - "7530:5432"

#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
