version: "3.8"

services:

 go_db_service:

   image: "postgres"
   container_name: "gopostgredb"
   environment:
     - POSTGRES_USER=edteam
     - POSTGRES_PASSWORD=edteam
     - POSTGRES_DB=godb

   ports:
     - "7530:5432"

   volumes:
     - ./postgres-data:/var/lib/postgresql/data